<?php

/**
 * UserWebTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserWebTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserWebTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserWeb');
    }
}